//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Admin_Type { get; set; }
        public string Admin_ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Pan_Number { get; set; }
        public string Aadhar_Number { get; set; }
        public string Permanent_Address { get; set; }
        public string Current_Address { get; set; }
        public byte[] Photo { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
        public string Reference { get; set; }
    }
}
