//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Details
    {
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string City { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public int Percentage { get; set; }
    }
}
