//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSMSDBEntities : DbContext
    {
        public MSMSDBEntities()
            : base("name=MSMSDBEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Customer_Details> Customer_Details { get; set; }
        public virtual DbSet<Owner_Registration> Owner_Registration { get; set; }
        public virtual DbSet<Pharma_Company_Details> Pharma_Company_Details { get; set; }
        public virtual DbSet<Store_Registration> Store_Registration { get; set; }
        public virtual DbSet<Vender_Details> Vender_Details { get; set; }
    }
}
