//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner_Registration()
        {
            this.Store_Registration = new HashSet<Store_Registration>();
        }
    
        public string Owner_Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public byte[] Photo { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public byte[] Pan_Number { get; set; }
        public byte[] Aadhar_Number { get; set; }
        public string Permanent_Address { get; set; }
        public string Current_Address { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store_Registration> Store_Registration { get; set; }
    }
}
