//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Registration
    {
        public string StoreEmail { get; set; }
        public string Store_Name { get; set; }
        public string Phone { get; set; }
        public string License_Number { get; set; }
        public byte[] License_Image_Copy { get; set; }
        public string Address { get; set; }
        public string Pan_Number { get; set; }
        public int Percentage { get; set; }
        public string Status { get; set; }
        public string Owner_Email { get; set; }
    
        public virtual Owner_Registration Owner_Registration { get; set; }
    }
}
