//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vender_Details
    {
        public int Vender_ID { get; set; }
        public string Vender_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public int Percentage { get; set; }
        public Nullable<int> Vender_Company_Id { get; set; }
    
        public virtual Pharma_Company_Details Pharma_Company_Details { get; set; }
    }
}
